### ISSUE TITLE
New Feature Request: Alternative Database Support

### ISSUE THREAD

**Issue by bravohotel91** [CyferShepard/Jellystat#165]
Would it be possible to extend the database requirements to include other databases such as MariaDB?

**Comment by CyferShepard** [comment]
Hi @bravohotel91 ,The reason i settled on postgres was because it offered alot of database side procedures and functions which help out alot with processing data. Not only would changing databases require a lot of those functions/procedures to be rewritten into the application side itself, by doing this it would greatly reduce the performance and responsiveness of the app as it would need to fetch and poll through large chuncks of data before we could get to the usable data we need. So changing databases at this point would not be a feasible option as it would basically require a rewrite of the entire app.
