### ISSUE TITLE
'Require Login' doesn't disable login fully

### ISSUE THREAD

**Issue by zodac** [CyferShepard/Jellystat#218]
**Describe the bug**
I have set the 'Require Login' option to **No**, but I am still shown the login screen when I load the page. However, if I refresh the page, it then lets me in (without providing any login credentials).

**Environment Details (please complete the following information):**
 - OS: Docker
 - Browser: Chrome
 - Jellystat Version: 1.1.0
 - Jellyfin Version: N/A

**To Reproduce**
1. Start a new instance of Jellystat
2. In the settings, set 'Require Login' to **No**
3. Load any page in incognito mode
4. You will be presented with the login page
5. Refresh the page and you will be able to access Jellystat

**Expected behavior**
I'd like the login page to not appear at all.

**Container Logs**
[jellystat.log](https://github.com/user-attachments/files/15879503/jellystat.log)

**Additional context**
I am using Authentik as my identity provider to authenticate/authorize users, so I don't require login from Jellystat. However, this issue occurs even without Authentik in place.

**Comment by FeroxFoxxo** [comment]
+1

**Comment by voc0der** [comment]
I am also getting this issue with `Authelia` and using `nginx` as a a reverse proxy in front.

**Comment by 2Klasic** [comment]
@CyferShepard I see this issue is closed but I'm experiencing the same issue on version 1.1.5. I have logon disabled but still doesn't work.


Describe the bug
I have set the 'Require Login' option to No, but I am still shown the login screen when I load the page. However, if I refresh the page, it then lets me in (without providing any login credentials).

Environment Details (please complete the following information):

OS: Docker
Browser: Safari
Jellystat Version: 1.1.5
Jellyfin Version: N/A
To Reproduce
Steps to reproduce the behavior:

Start a new instance of Jellystat
In the settings, set 'Require Login' to No
Load any page in incognito mode
You will be presented with the login page
Refresh the page and still requires my logon credentials
