### ISSUE TITLE
Vulnerability: SQL Injections

### ISSUE THREAD

**Issue by vincentscode** [CyferShepard/Jellystat#42]
There are [SQL Injection](https://www.w3schools.com/sql/sql_injection.asp) vulnerabilities throughout the API.

One such instance is in the login endpoint:
https://github.com/CyferShepard/Jellystat/blob/d9d5cad5d42a1165bd8e8318f13d541892a1ea79/backend/auth.js#L11-L17

Due to this anybody can login without knowing the password.

## Reproduction steps
1. Setup server to require password auth.
2. Logout
3. Login using an arbitrary password and the username `' OR 1 = 1) -- -`
4. The Login is successful

## Mitigation
You should never pass user input directly into database queries.
Always use `?` to pass user input.

Using an ORM is recommended in order to avoid such things and to improve database interactions and modelling in general.

**Comment by CyferShepard** [comment]
Hi @vincentscode , thanks for noticing this. I'm still fairly new to NodeJS but I did some quick research on how to mitigate this. In hindsight now that I look at what I typed, I can see the blunder I made. Because I was in such a rush to get work done in my free time I tend to miss stuff like this.

I have implemented the change and will add it soon

**Comment by CyferShepard** [comment]
Change has been made to prevent sql injection, now uses the values parameter provided by pg to validate data parameters

**Comment by vincentscode** [comment]
While the immediate login issue seems to have been addressed, there are still quite a few endpoints which pass unsanitized user input directly into SQL queries.
This is generally a vulnerability even though it is not directly exploitable and should be changed.

**Comment by vincentscode** [comment]
Hey, these other SQL Injections are still open and can probably be exploited to exfiltrate data or maybe even circumvent login.
They should be resolved especially now that more users seem to be running this.

**Comment by CyferShepard** [comment]
Hi @vincentscode , thanks for the reminder. This is actually currently being worked on. the reason for the major delay with the upcoming version was due to code optimizations and security audits. Security isn't really my specialty so this is taking longer than expected as I'm trying my best to plug any vulnerabilities as i can. I cant guarantee all will be patched but i will patch any issues i can find

**Comment by vincentscode** [comment]
I see, that's good to hear. I'm just worried that this might get exploited since some people are probably running Jellystat on the public internet by now and this is likely a vulnerability an automated scanner could realistically find.
