### ISSUE TITLE
Feature request: support of other DB

### ISSUE THREAD

**Issue by llaumgui** [CyferShepard/Jellystat#76]
Hi,

it would be nice to allow usage of other DB than Pg... Like MySQL ?

**Comment by CyferShepard** [comment]
Hi @llaumgui , unfortunately supporting multiple database types is not feasible, mainly because the functionality is dependent on stored procedures, views and scripts and by supporting another type of db, it will just result in duplicated code with higher chances of bugs. Also mysql doesn't have nearly as much features as postgres, many of which are needed for jellystat to function accurately

**Comment by FrancisAgostini** [comment]
Can I also add that it would be great if the docker pull also had postgress attached and that we could fill in variables on creation
