### ISSUE TITLE
High memory consumption

### ISSUE THREAD

**Issue by gauth-fr** [CyferShepard/Jellystat#83]
Hi, first than for Jellystat, it a very useful tool!

On my setup, Jellystat '(running as a container) use around 900MB RAM, which seems huge :)
Here is the output of `docker stats`:
```
CONTAINER ID   NAME            CPU %     MEM USAGE / LIMIT   MEM %     NET I/O           BLOCK I/O         PIDS
cdb45cbfc3d3   jellystat       3.17%     889.1MiB / 4GiB     21.71%    25.9MB / 9.66MB   201MB / 830MB     101
4e258e51c344   jellystat-db    11.10%    52.93MiB / 4GiB     1.29%     6.57MB / 8.86MB   6.6MB / 1.54MB    9
e3b8c5ddde10   jellyfin-10.8   0.46%     747.1MiB / 4GiB     18.24%    133MB / 1.04GB    304MB / 758MB     35
```
So i'm wondering if some.. optimizations could be done here and there to lower this number :)

Thanks!

**Comment by CyferShepard** [comment]
Hi @gauth-fr , will definitely look into ways to optimize memory usage

**Comment by CyferShepard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improved Performance](https://trello.com/c/s92111RP/3-improved-performance)

**Comment by Istria1704** [comment]
For me, it uses around 950MB of RAM:
`CONTAINER ID   NAME                  CPU %     MEM USAGE / LIMIT   MEM %     NET I/O           BLOCK I/O        PIDS
ae2d3436a06b   root-jellystat-1      0.82%     869.8MiB / 2GiB     42.47%    19.1MB / 7.87MB   682MB / 1.04GB   102
5f94f69cd5a9   root-jellystat-db-1   0.12%     50.13MiB / 2GiB     2.45%     6.85MB / 13.1MB   179MB / 96.8MB   8
49fe50c95995   jellyfin              0.54%     335.5MiB / 2GiB     16.38%    1.07MB / 3.77MB   920MB / 275MB    30`

But I also notice it takes a long time to start up. Around 5+ minutes. And it uses almost 100% CPU during that time. Is that normal?

I use the docker compose image. Only changed the passwords and added 'restart unless-stopped' for both services.

**Comment by Istria1704** [comment]
I will try it this evening. Thanks for improving this very nice tool! 

Apart from RAM usage, the CPU usage is very noticeable. It can't be seen well in the attached screenshot, because it shows the average. But the actual periodical spikes are very significant compared to having only Jellyfin running. From memory, it would use 30% of the two cores every 5 or 10min. I will check the exact numbers tonight. 

In the screenshot, the period with the higher cpu usage is the period where the jellystat container was running. The initial spike is the startup. 

I wonder what the difference is with Tautulli, which is basically not noticeable cpu-wise. Probably a different method the use. 

I'll let you know my findings after testing the unstable version tonight! 

![Screenshot_20231121-131044_ProxMon](https://github.com/CyferShepard/Jellystat/assets/39712196/e690f344-5c31-4f4d-ad45-42eec7badf2d)

**Comment by Istria1704** [comment]
By the way, is there a way to run the unstable build as a docker container? Or should I do it the npm way? In the latter case I'll make a dedicated LXC container for testing.

**Comment by CyferShepard** [comment]
Yes you can run it in docker. 

In regards to tautulli, i cant really compare the two as im not sure how well the integrations and the APIs work. But the reason jellystat is so resource intensive is due to how limited some of jellyfins APIs are . 

It is pretty great with what you can do but some criteria (eg filtering by date added/last modified) that would really help are not available as options in the API, this means id have to process large chucks of data from the responses on my side to end up with the data i actually want, this translates to the cpu and ram usage.

 Over time i would be able to reduce it much more significantly as I learn more optimized ways to handle larger chucks of data, but for now this is the best i can do. But i will still be working on this to improve the performance as much as i can.

**Comment by Istria1704** [comment]
> Yes you can run it in docker.

Ah, great. That makes it easier for me.
What are the image names I should use in the docker-compose.yml for jellystat and it's db? I noticed the docker-compose.yml files are the same in main and unstable branches.

Thanks for the explanation about the differences from Tautulli. That makes sense. So it's basically probably a limitation of Jellyfin itself. Let's hope their API's get better as the project develops. =)

**Comment by CyferShepard** [comment]
You can check the example compose file here: https://hub.docker.com/r/cyfershepard/jellystat
